src/Entity/Entretien.php
<?php

namespace App\Entity;

use App\Repository\EntretienRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntretienRepository::class)]
class Entretien
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $First_name = null;

    #[ORM\Column(length: 255)]
    private ?string $Last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $CIN = null;

    #[ORM\Column(length: 255)]
    private ?string $Phone = null;

    #[ORM\Column(length: 255)]
    private ?string $French_proficiency = null;

    #[ORM\Column(length: 255)]
    private ?string $English_proficiency = null;

    #[ORM\Column(length: 255)]
    private ?string $Previous_school = null;

    #[ORM\Column(length: 255)]
    private ?string $Specialization = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->First_name;
    }

    public function setFirstName(string $First_name): static
    {
        $this->First_name = $First_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->Last_name;
    }

    public function setLastName(string $Last_name): static
    {
        $this->Last_name = $Last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getCIN(): ?string
    {
        return $this->CIN;
    }

    public function setCIN(string $CIN): static
    {
        $this->CIN = $CIN;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->Phone;
    }

    public function setPhone(string $Phone): static
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getFrenchProficiency(): ?string
    {
        return $this->French_proficiency;
    }

    public function setFrenchProficiency(string $French_proficiency): static
    {
        $this->French_proficiency = $French_proficiency;

        return $this;
    }

    public function getEnglishProficiency(): ?string
    {
        return $this->English_proficiency;
    }

    public function setEnglishProficiency(string $English_proficiency): static
    {
        $this->English_proficiency = $English_proficiency;

        return $this;
    }

    public function getPreviousSchool(): ?string
    {
        return $this->Previous_school;
    }

    public function setPreviousSchool(string $Previous_school): static
    {
        $this->Previous_school = $Previous_school;

        return $this;
    }

    public function getSpecialization(): ?string
    {
        return $this->Specialization;
    }

    public function setSpecialization(string $Specialization): static
    {
        $this->Specialization = $Specialization;

        return $this;
    }
}

src/Controller/DashController.php
<?php

namespace App\Controller;

use App\Repository\StudentRepository;
use App\Repository\ProfessorRepository;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DashController extends AbstractController
{
    #[Route('/dash', name: 'app_dash')]
    public function dashboard(
        StudentRepository $studentRepository,
        ProfessorRepository $professorRepository,
        ReclamationRepository $reclamationRepository,
        EntityManagerInterface $entityManager
    ): Response {
        // Compter le nombre total d'étudiants
       // $totalStudents = $studentRepository->count([]);
      //  $totalProfessors = $professorRepository->count([]);

        // Compter le nombre d'étudiants masculins et féminins
      //  $maleStudents = $studentRepository->count(['gender' => 'Male']);
      //  $femaleStudents = $studentRepository->count(['gender' => 'Female']);

        // Calculer les pourcentages
      //  $malePercentage = ($totalStudents > 0) ? ($maleStudents / $totalStudents) * 100 : 0;
      //  $femalePercentage = ($totalStudents > 0) ? ($femaleStudents / $totalStudents) * 100 : 0;

        // Obtenir le nombre de nouveaux étudiants ajoutés chaque jour au cours des 7 derniers jours
       // $connection = $entityManager->getConnection();
       // $sql = "
       //     SELECT DATE(datecreation) AS creation_date, COUNT(*) AS student_count
      //      FROM user
       //     WHERE datecreation >= :last_week
       //     GROUP BY creation_date
       //     ORDER BY creation_date ASC
      //  ";
      //  $stmt = $connection->prepare($sql);
       // $stmt->bindValue('last_week', (new \DateTime('-7 days'))->format('Y-m-d'));
       // $result = $stmt->executeQuery();

        // Utiliser fetchAllAssociative() sur l'objet Result pour obtenir les données
       // $studentsPerDay = $result->fetchAllAssociative();

        // Préparer un tableau des étudiants créés chaque jour
        //$studentsPerDayData = [];
       // for ($i = 6; $i >= 0; $i--) {
      //     $date = (new \DateTime('-' . $i . ' days'))->format('Y-m-d');
       //     $studentsPerDayData[$date] = 0;
      //  }

       // foreach ($studentsPerDay as $data) {
       //     $date = $data['creation_date'];
       //     if (isset($studentsPerDayData[$date])) {
      //          $studentsPerDayData[$date] = (int)$data['student_count'];
      //      }
      //  }

        // Convertir le tableau en une chaîne de valeurs pour Sparkline
       // $studentsPerDayString = implode(',', $studentsPerDayData);

        // Récupérer le nombre de réclamations créées au cours des 7 derniers jours
      //  $newReclamationsCount = $reclamationRepository->countLast7DaysReclamations();

        // Passer les données à la vue
        return $this->render('dash/index.html.twig', [
      //      'total_students' => $totalStudents,
       //     'male_students' => $maleStudents,
       //     'female_students' => $femaleStudents,
       //     'male_percentage' => $malePercentage,
      //      'female_percentage' => $femalePercentage,
        //    'new_students' => array_sum($studentsPerDayData),
       //     'students_per_day' => $studentsPerDayString,
       ////    'newReclamationsCount' => $newReclamationsCount, // Ajout de cette variable
        ]);
    }

    #[Route('/', name: 'app_user')]
    public function user(): Response
    {
        return $this->render('user/user.html.twig');
    }

<<<<<<< HEAD
    #[Route('/listprofessors', name: 'app_list_professors')]
    public function listProfessors(): Response
    {
        return $this->render('dash/listprofessors.html.twig');
    }
=======
>>>>>>> 273b3dc5a7dc47d103f3e51cc1635e6c06d06212

    #[Route('/listbourses', name: 'app_list_bourses')]
    public function listBourses(): Response
    {
        return $this->render('dash/listbourses.html.twig');
    }

    #[Route('/listreclamation', name: 'app_list_reclamation')]
    public function listReclamation(): Response
    {
        return $this->render('dash/listreclamation.html.twig');
    }

    #[Route('/listcourses', name: 'app_list_courses')]
    public function listCourses(): Response
    {
        return $this->render('dash/listcourses.html.twig');
    }

    #[Route('/addbourse', name: 'app_add_bourses')]
    public function addBourse(): Response
    {
        return $this->render('dash/addbourse.html.twig');
    }

    #[Route('/editbourse', name: 'app_edit_bourses')]
    public function editBourse(): Response
    {
        return $this->render('dash/editbourse.html.twig');
    }

    #[Route('/allstaff', name: 'app_all_staff')]
    public function allStaff(): Response
    {
        return $this->render('dash/allstaff.html.twig');
    }

    #[Route('/addstaff', name: 'app_add_staff')]
    public function addStaff(): Response
    {
        return $this->render('dash/addstaff.html.twig');
    }

    #[Route('/editstaff', name: 'app_edit_staff')]
    public function editStaff(): Response
    {
        return $this->render('dash/editstaff.html.twig');
    }

    #[Route('/staffprofile', name: 'app_profile_staff')]
    public function staffProfile(): Response
    {
        return $this->render('dash/staffprofile.html.twig');
    }

    #[Route('/respondreclamation', name: 'app_respond_reclamation')]
    public function respondReclamation(): Response
    {
        return $this->render('dash/respondreclamation.html.twig');
    }

    #[Route('/listsupport', name: 'app_list_support')]
    public function listSupport(): Response
    {
        return $this->render('dash/listsupport.html.twig');
    }

    #[Route('/respondsupport', name: 'app_respond_support')]
    public function respondSupport(): Response
    {
        return $this->render('dash/respondsupport.html.twig');
    }

    #[Route('/payresto', name: 'app_payresto')]
    public function payResto(): Response
    {
        return $this->render('dash/payresto.html.twig');
    }

    #[Route('/gestionlivraison', name: 'app_gestion_livraison')]
    public function gestionLivraison(): Response
    {
        return $this->render('dash/gestionlivraison.html.twig');
    }

    #[Route('/liststudents', name: 'app_list_students')]
    public function listStudents(StudentRepository $studentRepository): Response
    {
        return $this->render('dash/liststudents.html.twig', [
            'students' => $studentRepository->findAll(),
        ]);
    }
}

templates/dash/addbooks.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Books{% endblock %}

{% block content %}


    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="welcome-text">
                <h4>Add Bourse</h4>
            </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0);">Books</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0);">Add Books</a></li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-xl-12 col-xxl-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Basic Info</h5>
                </div>
                <div class="card-body">
                    <form action="#" method="post">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Books Name</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Duration</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Email of school</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Books Responsible</label>
                                    <input name="datepicker" class="datepicker-default form-control" id="datepicker">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Funding Source</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Application Method</label>
                                    <select class="form-control">
                                        <option value="Type">Type</option>
                                        <option value="Online Application Portal">Online Application Portal</option>
                                        <option value="Email Submission">Email Submission</option>
                                        <option value="Paper Application">Paper Application</option>
                                        <option value="In-Person Submission">In-Person Submission</option>
                                        <option value="Institutional Nomination or Recommendation">Institutional Nomination or Recommendation</option>
                                        <option value="call application">call application</option>
                                        <option value="Interview-Based Application">Interview-Based Application</option>

                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Type</label>
                                    <select class="form-control">
                                        <option value="Type">Type</option>
                                        <option value="Athletic Bourses">Athletic Books</option>
                                        <option value="Need-Based Bourses">Need-Based Books</option>
                                        <option value="Subject-Specific Bourses:">Subject-Specific Books:</option>
                                        <option value="Community Service or Leadership Bourses">Community Service or Leadership Books</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Eligibility Criteria</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Amount</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Application Deadline</label>
                                    <input type="text" class="form-control">
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Interview  Date</label>
                                    <input name="datepicker" class="datepicker-default form-control" id="datepicker1">
                                </div>
                            </div>

                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="form-group">
                                    <label class="form-label">Description</label>
                                    <textarea class="form-control" rows="5"></textarea>
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <div class="form-group fallback w-100">
                                    <input type="file" class="dropify" data-default-file="">
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <button type="submit" class="btn btn-light">Cencel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/dash/addbourse.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add Bourse{% endblock %}

{% block content %}


<div class="row page-titles mx-0">
    <div class="col-sm-6 p-md-0">
        <div class="welcome-text">
            <h4>Add Bourse</h4>
        </div>
    </div>
    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Bourses</a></li>
            <li class="breadcrumb-item active"><a href="javascript:void(0);">Add Bourse</a></li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-xl-12 col-xxl-12 col-sm-12">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title">Basic Info</h5>
            </div>
            <div class="card-body">
                <form action="#" method="post">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Bourse Name</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Duration</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Email of school</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Bourse Responsible</label>
                                <input name="datepicker" class="datepicker-default form-control" id="datepicker">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Funding Source</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Application Method</label>
                                <select class="form-control">
                                    <option value="Type">Type</option>
                                    <option value="Online Application Portal">Online Application Portal</option>
                                    <option value="Email Submission">Email Submission</option>
                                    <option value="Paper Application">Paper Application</option>
                                    <option value="In-Person Submission">In-Person Submission</option>
                                    <option value="Institutional Nomination or Recommendation">Institutional Nomination or Recommendation</option>
                                    <option value="call application">call application</option>
                                    <option value="Interview-Based Application">Interview-Based Application</option>

                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Type</label>
                                <select class="form-control">
                                    <option value="Type">Type</option>
                                    <option value="Athletic Bourses">Athletic Bourses</option>
                                    <option value="Need-Based Bourses">Need-Based Bourses</option>
                                    <option value="Subject-Specific Bourses:">Subject-Specific Bourses:</option>
                                    <option value="Community Service or Leadership Bourses">Community Service or Leadership Bourses</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Eligibility Criteria</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Amount</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Application Deadline</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Interview  Date</label>
                                <input name="datepicker" class="datepicker-default form-control" id="datepicker1">
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="form-group">
                                <label class="form-label">Description</label>
                                <textarea class="form-control" rows="5"></textarea>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <div class="form-group fallback w-100">
                                <input type="file" class="dropify" data-default-file="">
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="submit" class="btn btn-light">Cencel</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/dash/listprofessors.html.twig
{% extends 'base.html.twig' %}

{% block title %}Professors{% endblock %}

{% block content %}

    <div class="row page-titles mx-0">
        <div class="col-sm-6 p-md-0">
            <div class="welcome-text">
                <h4>All Professors</h4>
            </div>
        </div>
        <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active"><a href="#">Professors</a></li>
                <li class="breadcrumb-item active"><a href="#">All Professors</a></li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">All Professors</h4>
                    <a href="{{ path('app_professor_new') }}" class="btn btn-primary">+ Add new</a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="example3" class="table table-bordered">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for professor in professors %}
                                <tr>
                                    <td>{{ professor.id }}</td>
                                    <td>{{ professor.name }}</td>
                                    <td>{{ professor.email }}</td>
                                    <td>{{ professor.phoneNumberProf }}</td>
                                    <td>
                                        <a href="{{ path('app_professor_show', {'id': professor.id}) }}" class="btn btn-sm btn-info"><i class="la la-eye"></i></a>
                                        <a href="{{ path('app_professor_edit', {'id': professor.id}) }}" class="btn btn-sm btn-primary"><i class="la la-pencil"></i></a>
                                        <form method="post" action="{{ path('app_professor_delete', {'id': professor.id}) }}" style="display:inline;" onsubmit="return confirm('Are you sure you want to delete this professor?');">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ professor.id) }}">
                                            <button class="btn btn-sm btn-danger"><i class="la la-trash-o"></i></button>
                                        </form>
                                    </td>
                                </tr>

                            {% else %}
                                <tr>
                                    <td colspan="5" class="text-center">No records found</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}